name = "MOTProject"
uuid = "5abf92d9-5444-42b3-bd0b-bb6df8a1e952"
authors = ["Liam Smith"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
